# Refer this article: https://medium.com/easyread/today-i-learned-golang-live-reload-for-development-using-docker-compose-air-ecc688ee076
# Please keep up to date with the new-version of Golang docker for builder
FROM golang:1.16.5-stretch

RUN apt update && apt upgrade -y && \
    apt install -y git \
    make openssh-client

WORKDIR /app 

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air
RUN go install github.com/go-delve/delve/cmd/dlv@latest

CMD air -c .air.toml